services:
  database:
    container_name: "postgres_dev"
    image: "postgres:16.6-alpine3.21"
    env_file:
      - ../.env
    ports:
      - "5432:5432"

  frontend:
    image: app
    ports:
      - "3000:3000"
